---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: replicaset-annotations-service-account
  namespace: default
  labels:
    name: replicaset-annotations-service-account
    app: appname
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: replicaset-annotations-role
  namespace: default
  labels:
    name: replicaset-annotations-role
    app: appname
rules:
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: replicaset-annotations-role-binding
  namespace: default
  labels:
    name: replicaset-annotations-role-binding
    app: appname
subjects:
  - kind: ServiceAccount
    name: replicaset-annotations-service-account
roleRef:
  kind: Role
  name: replicaset-annotations-role-binding
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      serviceAccountName: replicaset-annotations-service-account
      containers:
        - name: demo
          image: jkschneider/multifoundationmetrics:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080