global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'

    scrape_interval: 10s
    metrics_path: '/metrics'
    honor_labels: true
    static_configs:
      - targets: ['prometheus-push.apps.calabasas.cf-app.com']

rule_files:
  - prometheus_rules.yml