global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot2'

    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    honor_labels: true
    static_configs:
      - targets: ['10.0.2.2:7001']

  - job_name: 'promregator'

    scrape_interval: 10s
    metrics_path: '/metrics'
    honor_labels: true
    static_configs:
      - targets: ['10.200.10.1:8081']

  - job_name: 'promregator2'

    scrape_interval: 10s
    metrics_path: '/metrics'
    honor_labels: true
    static_configs:
      - targets: ['10.200.10.1:8082']

rule_files:
  - prometheus_rules.yml