---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
  - name: source

outputs:
  - name: gradle-props

run:
  path: source/concourse/build.sh
