---
resource_types:
  - name: properties
    type: registry-image
    source:
      repository: driepinter/props-resource
      tag: latest

resources:
  - name: source
    type: git
    source:
      uri: https://github.com/jkschneider/multi-foundation-metrics.git
  - name: 2m
    type: time
    source: {interval: 2m}
  - name: gradle-props
    type: properties
    source:
      path: gradle-props/build.properties

jobs:
  - name: gradle-build
    public: true
    plan:
      - get: source
        trigger: true
      - get: 2m
        trigger: true
      - task: build
        file: source/concourse/build.yml
      - put: gradle-props
